[package]
name = "internet-canary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
hostname = "0.3.1"
lettre = { version = "0.10.4", features = ["smtp-transport", "serde"] }
reqwest = "0.11.18"
serde = "1.0.171"
serde_json = "1.0.103"
tokio = { version = "1.29.1", features = ["time", "macros", "rt-multi-thread"] }
uptime_lib = "0.2.2"
